### ISSUE TITLE
[Question] `seaplane` challenge | EN | 

### ISSUE THREAD

**Issue by xBytez5636** [QIN2DIM/hcaptcha-challenger#22] opened 2022-03-22 02:59 UTC
2022-03-22 03:55:45 | DEBUG - >> Challenge [ArmorCaptcha] Avoiding the unmanageable challenge - label=seaplane

hCaptcha updated new images "seaplane" how can I manually add this?

**Comment by QIN2DIM** [comment] 2022-03-23 10:17
Duplicate of 
- https://github.com/QIN2DIM/hcaptcha-challenger/issues/10

**Comment by QIN2DIM** [comment] 2022-03-23 10:18
I will re-add this feature, but the time is not right yet.

**Closed** 2022-04-01 06:17 UTC
Labels: duplicate, fix
