### ISSUE TITLE
Does not works on M1 Mac

### ISSUE THREAD

**Issue by ja3abuser** [QIN2DIM/hcaptcha-challenger#233] opened 2022-09-27 07:42 UTC
```
2022-09-27 09:37:32 | ERROR - An error has been caught in function 'demo', process 'MainProcess' (15427), thread 'MainThread' (4370040192):
Traceback (most recent call last):
  File "/Users/wireguard/Downloads/hcaptcha-challenger-main/src/services/utils/toolbox/toolbox.py", line 105, in get_challenge_ctx
    return uc.Chrome(
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /Users/wireguard/.wdm/drivers/chromedriver/mac64_m1/105.0.5195/chromedriver unexpectedly exited. Status code was: -9


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/wireguard/Downloads/hcaptcha-challenger-main/src/main.py", line 11, in <module>
    Fire(Scaffold)
  File "/opt/homebrew/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/homebrew/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/homebrew/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
> File "/Users/wireguard/Downloads/hcaptcha-challenger-main/src/services/scaffold.py", line 73, in demo
    challenge.runner(
  File "/Users/wireguard/Downloads/hcaptcha-challenger-main/src/apis/scaffold/challenge.py", line 72, in runner
    with get_challenge_ctx(silence=silence, lang=lang) as ctx:
  File "/Users/wireguard/Downloads/hcaptcha-challenger-main/src/services/utils/toolbox/toolbox.py", line 109, in get_challenge_ctx
    return uc.Chrome(
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 244, in __init__
    raise RuntimeError("you cannot reuse the ChromeOptions object")
RuntimeError: you cannot reuse the ChromeOptions object
```

**Comment by QIN2DIM** [comment] 2022-09-27 08:04
`RuntimeError: you cannot reuse the ChromeOptions object` This tip means that the Chromedriver is being reused

**Comment by QIN2DIM** [comment] 2022-09-27 09:07
restart computer

**Comment by QIN2DIM** [comment] 2022-09-27 09:13
Can you pass the `python main.py test` ？

**Comment by QIN2DIM** [comment] 2022-09-27 09:22
fine

**Comment by kewka** [comment] 2022-10-10 23:22
I had the same error. We cannot use the `ChromeOptions` instance twice.

Fixed in https://github.com/kewka/hcaptcha-challenger/commit/b4b42b819a83c009b4d7831c6fe482c51899dfe2

**Comment by QIN2DIM** [comment] 2022-10-10 23:57
I think it may be that the way of process scheduling is different, and I can't reproduce it for the time being.

**Comment by QIN2DIM** [comment] 2022-10-11 05:29
I checked your changes and aren't the changes the same?

**Comment by kewka** [comment] 2022-10-11 09:05
> I checked your commits and aren't the changes the same?

They aren't the same. I mean we can't use the same `options` in the `except` block, we [have to create a new instance](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L244):
https://github.com/QIN2DIM/hcaptcha-challenger/blob/3d8c8975cbed5679e978da46be9c30f7fb73dd0a/src/services/utils/toolbox/toolbox.py#L108-L113

I noticed that a `WebDriverException` is thrown if `driver_executable_path` is specified
`selenium.common.exceptions.WebDriverException: Message: Service /Users/kewka/.wdm/drivers/chromedriver/mac_arm64/106.0.5249/chromedriver unexpectedly exited. Status code was: -9`

**Comment by QIN2DIM** [comment] 2022-10-11 09:31
I realized it was just a cosmetic problem. This means that the following line of code must have reported an error on M1.

https://github.com/QIN2DIM/hcaptcha-challenger/blob/3d8c8975cbed5679e978da46be9c30f7fb73dd0a/src/services/utils/toolbox/toolbox.py#L105

**Comment by QIN2DIM** [comment] 2022-10-11 09:37
Does the following code works?

```python
import undetected_chromedriver as uc
from webdriver_manager.chrome import ChromeDriverManager

driver_path = ChromeDriverManager().install()

if __name__ == '__main__':
    options = uc.ChromeOptions()
    options.headless = False
    ctx = uc.Chrome(options=options, driver_executable_path=driver_path, use_subprocess=True)

    try:
        ctx.get("https://www.google.com")
        print(ctx.title)
    finally:
        ctx.quit()

```

**Comment by QIN2DIM** [comment] 2022-10-11 09:42
So this was always a bug ...

```python
import undetected_chromedriver as uc
from webdriver_manager.chrome import ChromeDriverManager

driver_path = ChromeDriverManager().install()

if __name__ == '__main__':
    options = uc.ChromeOptions()
    ctx = None
    try:
        ctx = uc.Chrome(options=options, driver_executable_path=driver_path, use_subprocess=True)
        raise RuntimeError
    # RuntimeError: you cannot reuse the ChromeOptions object
    except RuntimeError:
        ctx = uc.Chrome(options=options, driver_executable_path=driver_path, use_subprocess=True)
    finally:
        ctx.quit()

```

**Closed as completed** 2023-04-18 15:42 UTC
Labels: bug
