### ISSUE TITLE
[Challenge] 

### ISSUE THREAD

**Issue by Shearkeyy** [QIN2DIM/hcaptcha-challenger#493] opened 2023-04-11 01:45 UTC
### Prompt[en]

Please click each image containing a kettle

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://discord.com

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/106593315/231033914-8d24ef7f-8d6d-49b9-a3b7-accb9b06c939.png)

**Comment by Sysys242** [comment] 2023-04-11 08:23
Duplicate of #491

**Closed** 2023-04-12 16:00 UTC
Labels: 🔥 challenge
